# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Vico.Guru
tagline:             'A blog for beginner programmer'
description:         'A blog for all young (and young at heart) people who want some help in their programming endavours.'
url:                 http://www.vico.guru
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Vico Guru
  url:               https://twitter.com/mdo
  email:             real.vico.guru@gmail.com

# Custom vars
version:             1.0.0

port:                4445
